baseURL = "http://example.org/"
languageCode = "en-us"
title = "Open Web"

[params]
    author = "Open Web BU"
    description = "Open Web BU is BU's best club for passionate coders."
    stylesheet = "styles.css"
    script = "app.js"